
services:


  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  
      - ./data/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY="Måste ändras" 
      - TZ=Europe/Stockholm
    ports:
      - "7575:7575"


  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ./data/vaultwarden:/data
    environment:
      - DOMAIN=http://localhost:8080       
      - SIGNUPS_ALLOWED=true              
      - TZ=Europe/Stockholm
    ports:
      - "8080:80"

  
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - VERSION=docker
      - PLEX_CLAIM="Måste ändras"
    volumes:
      - ./data/plex/config:/config
      - ./data/plex/transcode:/transcode
      - ./data/plex/media:/media   
    ports:
      - "32400:32400"



  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Sweden/Stockholm 


networks:
  homelab:
    name: homelab
    driver: bridge
